### ISSUE TITLE
[ethiopic] Add string equivalent methods

### ISSUE THREAD

**Issue by andjc** [enabling-languages/el_data#3]
Add methods for *family* and *order* of syllables to `eld.EthiopicUCDString` class.

* [x] `get_order()` - return list of orders for each character in string, non-syllables return `None`.
* [x] `get_family()` - return list of families for each character in string, non-syllables return `None`.
* [x] `convert_order(order, index = None)` - either convert each syllable in string to specific order, or only convert character at specified index in string. Return either as a list or a string.
* [ ] ~~`convert_family(family, index = None)`~~ _No use case._
* [ ] ~~`family_to_uset(family)` - create a `icu.UnicodeSet` instance of all members of a family.~~ __Moved to `EthiopicUCD`__
* [ ] ~~`family_to_pattern(family)` - create a regular expression character class for syllables in specified family.~~
* [ ] ~~`order_to_uset(order)` - create a `icu.UnicodeSet` instance of all members of an order.~~
* [ ] ~~`order_to_pattern(order)` - create a regular expression character class for syllables in specified order.~~

**Comment by andjc** [comment]
1. _Is `convert_family` needed, and if so, expected usage and behaviour?_
2. _Should `get_order` and `get_family` be able to specify a string index and only report the order or family of syllable at that index in string?_

**Comment by dyacob** [comment]
1. I can't think of a use case for convert_family().
2. Yes. I think this is the more frequent use case.
